[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
check_untyped_defs = true
disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_subclassing_any = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "tests.data.*"
disallow_untyped_defs = false
check_untyped_defs = false

[tool.ruff]
select = [
  "A",      # flake8-builtins
"AIR",    # Airflow
  "ASYNC",  # flake8-async
"B",      # flake8-bugbear
  "BLE",    # flake8-blind-except
"C4",     # flake8-comprehensions
"C90",    # McCabe cyclomatic complexity
"CPY",    # flake8-copyright
  "DJ",     # flake8-django
  "DTZ",    # flake8-datetimez
  "E",      # pycodestyle
  "EM",     # flake8-errmsg
"EXE",    # flake8-executable
 "F",      # Pyflakes
  "FLY",    # flynt
 "G",      # flake8-logging-format
  "I",      # isort
"ICN",    # flake8-import-conventions
 "INP",    # flake8-no-pep420
"INT",    # flake8-gettext
 "ISC",    # flake8-implicit-str-concat
 "N",      # pep8-naming
  "NPY",    # NumPy-specific rules
 "PD",     # pandas-vet
  "PERF",   # Perflint
  "PGH",    # pygrep-hooks
  "PIE",    # flake8-pie
